# Generated by Django 6.0.2 on 2026-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DadosColetados",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("sys_loc_code", models.CharField(max_length=100)),
                ("param_code", models.CharField(max_length=50)),
                ("param_unit", models.JSONField()),
                ("measurement_method", models.CharField(max_length=250)),
                ("measurement_date", models.DateTimeField()),
                ("remark", models.CharField(max_length=150)),
                ("task_code", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "dados_coletados",
            },
        ),
    ]
