# Generated by Django 6.0.2 on 2026-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResultadosAmostras",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_interna", models.CharField(max_length=100)),
                ("nome_amostra", models.CharField(max_length=50)),
                ("data_coleta", models.DateField()),
                ("horario_coleta", models.TimeField()),
                ("param_quimi", models.CharField(max_length=100)),
                ("resultado", models.CharField(max_length=50)),
                ("unidade", models.CharField(max_length=50)),
                ("limite_quant", models.IntegerField()),
            ],
            options={
                "db_table": "resultados_amostras",
            },
        ),
    ]
