# Generated by Django 6.0.2 on 2026-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnaliseProcess",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cas", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=250)),
                ("efeito", models.CharField(max_length=2)),
                ("ambiente", models.CharField(max_length=15)),
                ("vor", models.CharField(max_length=150)),
                ("valor_vor", models.DecimalField(decimal_places=15, max_digits=20)),
                (
                    "concentracao_max",
                    models.DecimalField(decimal_places=15, max_digits=20),
                ),
                ("solu_concentracao", models.PositiveIntegerField()),
                (
                    "valor_considerado",
                    models.DecimalField(decimal_places=15, max_digits=20),
                ),
                ("valor_final", models.DecimalField(decimal_places=15, max_digits=20)),
                ("aplicar_cinza", models.BooleanField()),
                ("aplicar_laranja", models.BooleanField()),
            ],
            options={
                "db_table": "vw_analise_processada",
                "managed": False,
            },
        ),
    ]
