# Generated by Django 6.0.2 on 2026-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvaliacaoRisco",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cas", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contaminante",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("efeito", models.CharField(blank=True, max_length=2, null=True)),
                ("ambientes_abertos", models.FloatField(blank=True, null=True)),
                ("ambientes_fechados", models.FloatField(blank=True, null=True)),
                ("vor_nome", models.CharField(blank=True, max_length=150, null=True)),
                ("valor_vor", models.FloatField(blank=True, null=True)),
                ("solubilidade", models.IntegerField(default=500)),
                ("menor_valor_final", models.FloatField(blank=True, null=True)),
                ("is_cinza", models.BooleanField(default=False)),
                ("is_laranja", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "avaliacao_risco",
            },
        ),
    ]
