# Generated by Django 6.0.2 on 2026-02-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contaminante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cas", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "contaminante",
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoRisco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("efeito", models.CharField(max_length=2)),
                ("ambiente", models.CharField(max_length=15)),
                ("vor", models.CharField(blank=True, max_length=150, null=True)),
                ("valor_vor", models.DecimalField(decimal_places=15, max_digits=20)),
                (
                    "concentracao_max",
                    models.DecimalField(decimal_places=15, max_digits=20),
                ),
                ("solu_concentracao", models.PositiveIntegerField(default=500)),
                (
                    "contaminante",
                    models.ForeignKey(
                        db_column="contaminante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case2.contaminante",
                    ),
                ),
            ],
            options={
                "db_table": "avaliacao_risco",
            },
        ),
    ]
